### PR TITLE
Change download links to webarchive since lulucloud.mywire.org is down

### PR DESCRIPTION
**Pull request by matt0x20**

### CODE REVIEW

**Comment by MiMillieuh** [comment]
I have to think about it.
I've down the server myself as a lot of people seem to use this without licences which I'm totally against.

Thanks for the proposal anyway

**Comment by CukierDev** [comment]
Yeah that's a problem
One of the solutions might be just forcing the user to provide photoshop files themselves

**Comment by MiMillieuh** [comment]
> Yeah that's a problem One of the solutions might be just forcing the user to provide photoshop files themselves

That's what I'm looking for... I don't really have time but I know that wine has progressed a lot and doesn't require my patched version of Photoshop. 

I may update the scripts but the issue with that is that sometimes the 21.0.1 works but the 21.0.2 doesn't and it's sometime really hard to find a specific version on the adobe creative cloud app... 

Honestly there are no easy solutions...

**Comment by ryzendew** [comment]
These links are really slow try Qiwi they seem to be a good place

**Comment by PostboxRetinal** [comment]
I will like to do a PR referring to this link for downloading the file, is that ok with you? @ryzendew

**Comment by slrgt** [comment]
> https://qiwi.gg/file/kMnq2220-AdobePhotoshop2021 here ya go i will host for now

you should consider making a torrent so it can be stored for a long time since in a year or so this link will probably not work

**Review by ryzendew — APPROVED** [review]
current master does not work even with my downloads please merge instead till a better way is found i do suggest using nextcloud and self hosting the file.

**Comment by antgame11** [comment]
> https://qiwi.gg/file/kMnq2220-AdobePhotoshop2021 here ya go i will host for now

ah. I love being flashed with images in my living room with my family sitting next to me.. Thanks Qiwi!!

**Comment by slrgt** [comment]
> > https://qiwi.gg/file/kMnq2220-AdobePhotoshop2021 here ya go i will host for now
> 
> ah. I love being flashed with images in my living room with my family sitting next to me.. Thanks Qiwi!!

always have an adblocker installed. Ublock Origin is the best one. But yeah thats another reason why moving the link to Archive.org would be best

**Comment by antgame11** [comment]
> > > https://qiwi.gg/file/kMnq2220-AdobePhotoshop2021 here ya go i will host for now
> > 
> > 
> > ah. I love being flashed with images in my living room with my family sitting next to me.. Thanks Qiwi!!
> 
> always have an adblocker installed. Ublock Origin is the best one. But yeah thats another reason why moving the link to Archive.org would be best

Bro, I have Ublock Origin

**Comment by BrycensRanch** [comment]
> > > > https://qiwi.gg/file/kMnq2220-AdobePhotoshop2021 here ya go i will host for now
> > > 
> > > 
> > > ah. I love being flashed with images in my living room with my family sitting next to me.. Thanks Qiwi!!
> > 
> > 
> > always have an adblocker installed. Ublock Origin is the best one. But yeah thats another reason why moving the link to Archive.org would be best
> 
> Bro, I have Ublock Origin

I just checked and I don't see any ads with Ublock Origin. Update your browser and extensions and ensure your block lists are up to date.

**Comment by matt0x20** [comment]
Im closing this pr because like [MiMillieuh](https://github.com/MiMillieuh) said he closed the original server that hosted the files because a lot of people were using it for piracy. Also there's a better alternative already implemented read https://github.com/LinSoftWin/Photoshop-CC2022-Linux/pull/132

**Comment by daskog** [comment]
Where is the 2022 image? @MiMillieuh @ryzendew, tnx in advance.

**Comment by toonshouin** [comment]
I also have AdobePhotoshop2021 files on my Server if you want to.

https://dl.toonshou.in/p/Program/Adobe/AdobePhotoshop2021.tar.xz?sign=QklsZxvuI3eFnVr3-X5D2aT8UkzTAy7OMDi3iJRG2Wg=:0

Right now, I still have problem with FTP that I metioned on https://github.com/LinSoftWin/Photoshop-CC2022-Linux/pull/128#issuecomment-2906770383 but this time I have WebDAV Enabled, so I think we can change script and it will work now, Still on the same /Program/Adobe/ Directory!

PS : This server locate on Thailand, so if you not sure what speed you will getting from this, you can try speedtest using my link [`speed.aoeyoei.xyz`](https://speed.aoeyoei.xyz)

_And sadly, I don't have Photoshop 2022 like any others people here._

**Comment by SeeDborg** [comment]
Can someone upload the link again, please ?

**Comment by toonshouin** [comment]
> Can someone upload the link again, please ?

Okay, let me reconfig my server real quick. And I will updated the link on my comment!

**Comment by toonshouin** [comment]
> I also have AdobePhotoshop2021 files on my FTP Server if you want to.

For now, Download from this link until I fixed my FTP Server.

https://files.toonshou.in/s/FaypN95p7tQxT62 (This will be removed when that back online.)

So, @SeeDborg go for it.

**Comment by slrgt** [comment]
Can yall send me links to my email with it? I wsnt to archive it and upload to codeberg and Mega a version for longterm storage of this package and instructions for linux with the basics for noobs like me to remember how to use everything together for smooth linux experience

My email is ***@***.***

**Comment by toonshouin** [comment]
Since Github automatically censored your email, you can mail to me using [this](mailto:me@toonshou.in). ( me at toonshou dot in )

**Comment by slrgt** [comment]
Oh my emvil is linux.5wyzu@ simplelogin .com

No spaces

**Comment by SeeDborg** [comment]
The previous link on qiwi  was a f*cking virus, I'm never trusting anyone here again.

**Comment by BrycensRanch** [comment]
> The previous link on qiwi was a f*cking virus, I'm never trusting anyone here again.

Hi! What file did you download? The qiwi site requires you to open a malicious ad and then it allows you to download the file. Bad design, I know. In reality, things like this should be a torrent.  If you downloaded anything after you were redirected, I'd recommend saving the files you want and formatting Windows and maybe adding Malwarebytes. The file `AdobePhotoshop2021.tar.xz` looks clean to me.

**Comment by slrgt** [comment]
This is why I’m making a publically accessible archive with all the links needed to be safe links. And magnet link for a v2 torrent file made with qbittorent

So no one has to accidentally click malware ad and download viruses

**Comment by toonshouin** [comment]
Yeah, And that's why I hosted on my own.

**Comment by toonshouin** [comment]
> https://dl.toonshou.in/p/Program/Adobe/AdobePhotoshop2021.tar.xz?sign=QklsZxvuI3eFnVr3-X5D2aT8UkzTAy7OMDi3iJRG2Wg=:0

I updated the real link now, you can go through here ^^

> Right now, I still have problem with FTP that I metioned on [#128 (comment)](https://github.com/LinSoftWin/Photoshop-CC2022-Linux/pull/128#issuecomment-2906770383) but this time I have WebDAV Enabled, so I think we can change script and it will work now, Still on the same /Program/Adobe/ Directory!

and if I make FTP works again, you can use that also.

cc, @slrgt @SeeDborg @BrycensRanch

---
PS : This link will be deactivated in 7 days from now on.
> https://files.toonshou.in/s/FaypN95p7tQxT62

**Comment by qMicu** [comment]
Direct Folder download: https://drive.google.com/drive/folders/1WyuaON0jHu92tC82dtwadUGjeDw_W9lU?usp=sharing
---
Torrent download: https://drive.google.com/file/d/1Uub-Xh_EDJrKcIBp58Ej9HaMJhJG3Jpl/view?usp=sharing (Please seed)

If you want to use 2021 instead of 2022 just cd into the folder and `wine photoshop.exe`
I hope it works for you... :)

**Comment by khalilgharbaoui** [comment]
> ## Direct Folder download: https://drive.google.com/drive/folders/1WyuaON0jHu92tC82dtwadUGjeDw_W9lU?usp=sharing
> 
> Torrent download: https://drive.google.com/file/d/1Uub-Xh_EDJrKcIBp58Ej9HaMJhJG3Jpl/view?usp=sharing (Please seed)
> 
> If you want to use 2021 instead of 2022 just cd into the folder and `wine photoshop.exe` I hope it works for you... :)

why is there a file called sniffer.exe in there?

**Comment by BrycensRanch** [comment]
> sniffer

Probably because it's malware. Hence, their GitHub account with no activity. I wouldn't trust what they've posted.

**Comment by matt0x20** [comment]
# PLEASE BE CAREFUL

Please do not trust every link posted in this PR! If you want to acquire the original version of the `AdobePhotoshop2021.tar.xz` file, I believe the only trusted way of doing that is to use the archive.org link in the source of this PR as it uses a snapshot of the original web server that was used to host that file.

In case you want to check if your copy of `AdobePhotoshop2021.tar.xz` is the original please check it's SHA256 checksum with command
```
sha256sum AdobePhotoshop2021.tar.xz
```
and check if the output matches the SHA256 sum in the readme of this repo.

If you have downloaded a version that is already decompressed you can use the `sha256sums.txt` file I have attached in this comment to check the sum of the decompressed folder with command
```
sha256sum -c sha256sums.txt
```
correct

incorrect

<br>

[sha256sums.txt](https://github.com/user-attachments/files/21698694/sha256sums.txt)

**Comment by slrgt** [comment]
archive.org link in the pr says the file doesnt exist

**Comment by matt0x20** [comment]
https://web.archive.org/web/20230627155425if_/https://lulucloud.mywire.org/FileHosting/GithubProjects/AdobePhotoshop2021.tar.xz

**Comment by kildahldev** [comment]
It is now also necessary to download the allredist.tar.xz manually
https://web.archive.org/web/20230627155424/https://lulucloud.mywire.org/FileHosting/GithubProjects/allredist.tar.xz

**Comment by AizWho** [comment]
> https://web.archive.org/web/20230627155425if_/https://lulucloud.mywire.org/FileHosting/GithubProjects/AdobePhotoshop2021.tar.xz

Thank you!

**Pull request closed without merging**
